<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>

	  <!-- ESTAS SON LAS DOS LÍNEAS CORRECTAS -->
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <GenerateTargetFrameworkAttribute Condition="'$(GenerateTargetFrameworkAttribute)' == ''">false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

</Project>
